//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virtual_Bank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trans_details
    {
        public int Trans_Id { get; set; }
        public Nullable<long> From_number { get; set; }
        public Nullable<long> To_number { get; set; }
        public Nullable<long> Trans_Amount { get; set; }
        public Nullable<System.DateTime> Trans_Date { get; set; }
    
        public virtual LOGIN LOGIN { get; set; }
    }
}
